# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filelisting.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66ilelisting.proto\x12\x0b\x66ilelisting\"\x07\n\x05\x45mpty\"\"\n\x04\x46ile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x04\",\n\x08\x46ileList\x12 \n\x05\x66iles\x18\x01 \x03(\x0b\x32\x11.filelisting.File2N\n\x12\x46ileListingService\x12\x38\n\tListFiles\x12\x12.filelisting.Empty\x1a\x15.filelisting.FileList\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'filelisting_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=34
  _EMPTY._serialized_end=41
  _FILE._serialized_start=43
  _FILE._serialized_end=77
  _FILELIST._serialized_start=79
  _FILELIST._serialized_end=123
  _FILELISTINGSERVICE._serialized_start=125
  _FILELISTINGSERVICE._serialized_end=203
# @@protoc_insertion_point(module_scope)
